# ==================================================
# 1~ General settings
# ==================================================

unbind-key -a

# ==================================================
# 2~ Keybinds
# ==================================================

# Windows Movement
bind -n C-M-w next-window
bind -n C-M-s previous-window
bind -n C-M-x kill-pane
bind -n C-M-c new-window

# Split
bind -n C-M-v split-window -h
bind -n C-M-d select-pane -R
bind -n C-M-a select-pane -L

# ==================================================
# 3~ Appearance
# ==================================================

# Bar
set -g status-style bg=default,fg=white

# Bar cleaning
set -g status-left ""
set -g status-right "#[fg=white]%H:%M "

# Borders
set -g pane-border-style fg=white
set -g pane-active-border-style fg=white,bg=default
